image: alpine:3.15.1
stages:
  - test
  - build
  - deploy

run_unit_tests:
  image: node:16.13.0
  tags:
    - "local"
    - "macos"
  stage: test
  before_script:
    - ls
    - yarn
  script:
    - yarn test:all
  artifacts:
    reports:
      junit: junit.xml
