image: alpine:3.15.1
stages:
  - test
  - build
  - deploy
  
run_unit_tests:
  image: node:16.13.0
  tags:
    - "ec2"
    - "docker"
    - "remote"
  stage: test
  before_script:
    - cd app
    - yarn
  script:
    - nx run-many --target=test --all --skip-nx-cache



