workflow:
  rules:
    - if: $CI_COMMIT_BRANCH != "main" && $CI_PIPELINE_SOURCE !="merge_request_event"
      when: never
    - when: always

stages:
  - test
  - build
  - deploy
  
run_unit_tests:
  stage: test
  before_script:
    - echo "before"
    - chmod +x prepare-test.sh
    - ./prepare-test.sh
  script:
    - echo "running tests for $MICRO_SERVICE_NAME"
  after_script:
    - echo "after"

run_lint_tests:
  stage: test
  before_script:
    - echo "before"
  script:
    - echo "running tests"
  after_script:
    - echo "after"

build_image:
  only:
    - main
  stage: build
  script:
    - echo "building 1"

push_image:
  only:
    - main
  stage: build
  needs:
    - build_image
  script:
    - echo "pushing"

deploy_image:
  only:
    - main
  stage: deploy
  script:
    - echo "pushing"
