stages:
  - test
  - build
  - deploy
  
run_unit_tests:
  stage: test
  before_script:
    - echo "before"
    - chmod +x prepare-tests.sh
    - ./prepare-tests.sh
  script:
    - echo "running tests"
  after_script:
    - echo "after"

run_lint_tests:
  stage: test
  before_script:
    - echo "before"
  script:
    - echo "running tests"
  after_script:
    - echo "after"

build_image:
  stage: build
  script:
    - echo "building 1"

push_image:
  stage: build
  needs:
    - build_image
  script:
    - echo "pushing"

deploy_image:
  stage: deploy
  script:
    - echo "pushing"
