image: alpine:3.15.1
stages:
  - test
  - build
  - deploy
  
run_unit_tests:
  tags:
    - "ec2"
    - "aws"
    - "remote"
  stage: test
  before_script:
    - echo "before"
    - chmod +x prepare-test.sh
    - ./prepare-test.sh
  script:
    - echo "running tests"
  after_script:
    - echo "after"

run_lint_tests:
  tags:
    - "ec2"
    - "aws"
    - "remote"
  stage: test
  before_script:
    - echo "before"
  script:
    - echo "running tests"
  after_script:
    - echo "after"

build_image:
  tags:
    - "ec2"
    - "aws"
    - "remote"
  stage: build
  script:
    - echo "building 1"

push_image:
  tags:
    - "ec2"
    - "aws"
    - "remote"
  stage: build
  needs:
    - build_image
  script:
    - echo "pushing"

deploy_image:
  tags:
    - "ec2"
    - "aws"
    - "remote"
  stage: deploy
  script:
    - echo "pushing"
