version: "3.3"
services:
#  app:
#    image: ${DC_IMAGE_NAME}:${DC_IMAGE_TAG}
#    ports:
#      - ${DC_APP_PORT}:${DC_APP_PORT}
#    command:
#      - yarn ${COMPOSE_PROJECT_NAME} start
#
#
#  contracts:
#    build:
#      context: .
#      dockerfile: dev.Dockerfile
#      args:
#        APP_NAME: contracts
#    volumes:
#      - ./:/app
#    environment:
#      MONGO_URL: 'mongodb://root:root@mongo:27017/db?authSource=admin'
#      PORT: '3002'
#      CONTRACTS_MICROSERVICE_HOST: 'contracts'
#    depends_on:
#      - mongo
#  offers:
#    build:
#      context: .
#      dockerfile: dev.Dockerfile
#      args:
#        APP_NAME: offers
#    volumes:
#      - ./:/app
#    environment:
#      MONGO_URL: 'mongodb://root:root@mongo:27017/db?authSource=admin'
#      OFFERS_MICROSERVICE_HOST: 'offers'
#      PORT: '3001'
#    depends_on:
#      - mongo

  gateway:
    image: registry.gitlab.com/alexanderkir1994/contracts-svc/microservice/monorepo:1.0
    networks:
      - micro_service
    environment:
      PORT: '3333'
      CONTRACTS_MICROSERVICE_PORT: '3002'
      OFFERS_MICROSERVICE_PORT: '3001'
      CONTRACTS_MICROSERVICE_HOST: 'contracts'
      OFFERS_MICROSERVICE_HOST: 'offers'
    ports:
      - 3333:3333

networks:
  micro_service:
    external:
      name: micro_service
